- name: "Connecting to Extreme EXOS switches"
  hosts: switches
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
#    - name: Gather facts (exos)
#      exos_facts:
#      when: ansible_network_os == 'exos'

    # Get running configuration
    #

    - name: Get running configuration (exos)
      exos_config:
        backup: yes
      register: backup_exos_location
      when: ansible_network_os == 'exos'

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes

    - name: Copy backup files into Desktop (exos)
      copy:
        src: "{{ backup_exos_location.backup_path }}"
        dest: "/home/adit/Desktop/backups/{{ inventory_hostname }}/"
#{{ inventory_hostname }}.bck"
      when: ansible_network_os == 'exos'
